<?php 
$items = $this->items;
?>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

<script src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/i18n/jquery.ui.datepicker-vi.js"></script>
<div class="row-fluid" style="margin-top: 20px;margin-bottom: 20px;">
    <?php     
    $buttons[]=array('onclick'=>'$("#excel").val("1");$("#form").submit();','label'=>'Xuất file excel');
    echo $this->toolbar($buttons);
    ?>
</div>
<form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->baseUrl('/thongke'); ?>" method="post">
<div class="row-fluid">
    <div class="col-lg-4 col-md-4">
        <strong>Từ ngày: </strong>
        <input type="text" id="tu_ngay_quyet_dinh" readonly="readonly" name="tu_ngay_quyet_dinh" value="<?php echo $this->tu_ngay_quyet_dinh;?>"/>
        
    </div>
    <div class="col-lg-4 col-md-4">
        <strong>Đến ngày: </strong>
        <input type="text" id="den_ngay_quyet_dinh" readonly="readonly" name="den_ngay_quyet_dinh" value="<?php echo $this->den_ngay_quyet_dinh;?>"/>
        
    </div>
</div>
    <input type="hidden" name="excel" id="excel" value="0"/>
</form>
<br><br><br>
<div class="row-fluid">
    <table class="table table-bordered" id="nanopool-table" style="display: none;">
            <thead>
                <th>Số quyết định</th>
                <th>Ngày tháng</th>
                <th>Nội dung dự toán</th>
                <th>Giá trị dự toán</th>
                <th>Người phụ trách</th>
            </thead>
            <tbody>
                <?php 
                    $sum=0;
                    foreach ($items as $item){
                        $sum+=$item['tong_tien'];
                        ?>
                    <tr>
                        <td style="width: 20%;text-align: center;">
                            <?php 
                            echo $item['so_quyet_dinh'];
                            ?>
                        </td>
                        <td>
                            <?php 
                            list($date,$time)= explode(" ", $item['ngay_quyet_dinh']);
                            list($y,$m,$d)= explode("-", $date);
                            echo "$d/$m/$y";
                            ?>
                        </td>
                        <td title="<?php echo $item['noi_dung_quyet_dinh'];?>">
                            <?php echo Core_Common_String::crop($item['noi_dung_quyet_dinh'], 20);?>
                        </td>
                        <td>
                            <?php echo number_format($item['tong_tien'],0,",",".");?>
                        </td>
                        <td>
                            <?php 
                            echo $item['danh_xung'].' '.$item['full_name'];
                            ?>
                        </td>
                        
                    </tr>
                    <?php 
                    }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">&nbsp;</td>
                    <td><?php echo number_format($sum,0,",",".");?></td>
                    <td>&nbsp;</td>
                </tr>
            </tfoot>
        </table>

</div>
<script type="text/javascript">
    $(window).load(function() {
          $('#nanopool-table').show();
          $('#nanopool-table').DataTable();
          $('#nanopool-table_filter').remove();//.find('input').eq(0).css('width','270px');
          
    });
    jQuery(function ($){
       $( "#tu_ngay_quyet_dinh,#den_ngay_quyet_dinh" ).datepicker({
           onClose:function (){
               $("#excel").val('0');
               $("#form").submit();
           },
          changeMonth: true,
          changeYear: true,
          dateFormat: "dd/mm/yy",
          showWeek: true,
            showOn: "button",
            buttonImage: "<?php echo $this->baseUrl('/images/calendar/calendar.gif');?>",
            buttonImageOnly: true,
            buttonText: 'Click để chọn ngày',
            option:$.datepicker.regional['vi']
        });
       
    });
</script>
