<?php 
$items = $this->items;
?>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
<style>
    .dx-body {
        background-color: #f1f1f1
    }

    @media(min-width:992px) {
        .container {
            width: 960px
        }
    }

    .dx-content .dx-container-column {
        padding-top: .5rem;
        padding-bottom: .5rem;
        padding-left: 1rem;
        padding-right: 1rem
    }

    @media(min-width:400px) {
        .dx-content .dx-container-column {
            padding-top: .75rem;
            padding-bottom: .75rem;
            padding-left: 1.5rem;
            padding-right: 1.5rem
        }
    }

    @media(min-width:992px) {}

    .dx-container-row {
        padding-top: .5rem;
        padding-bottom: .5rem
    }

    @media(min-width:400px) {
        .dx-container-row {
            padding-top: .75rem;
            padding-bottom: .75rem
        }
    }

    .dx-container-padding {
        padding-top: .5rem
    }

    .dx-content .container {
        overflow: hidden;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
        background-color: #fff
    }

    @media(min-width:992px) {
        .dx-content .container {
            margin-top: 1rem;
            margin-bottom: 1rem
        }
    }

    .dx-vertical-item+.dx-vertical-item {
        margin-top: .75rem
    }

    .dx-separator {
        margin-left: -3rem;
        margin-right: -3rem;
        border-top: 1px solid #e2e2e2
    }

    @media(min-width:992px) {
        .dx-separator {
            margin-left: 0;
            margin-right: 0
        }
    }

    .dx-tooltip {
        border-radius: .25rem;
        padding: 1rem 1.25rem;
        background-color: #333;
        color: #fff
    }

    .dx-tooltip-pointer-top {
        border-top: 6px solid transparent;
        border-bottom: 12px solid #333;
        border-left: 6px solid transparent;
        border-right: 6px solid transparent
    }

    .dx-tooltip .close {
        color: #fff
    }

    .dx-tooltip .fa-li {
        line-height: 1.4
    }

    a.dx-tooltip-link {
        display: block;
        word-break: break-all
    }

    a.dx-tooltip-link {
        color: #7ac616
    }

    a.dx-tooltip-link:hover {
        color: #7ac616
    }

    a.dx-tooltip-link:active {
        color: #7ac616
    }

    .dx-menu {
        padding-top: 1rem;
        padding-bottom: 1rem
    }

    .dx-menu .list-group+.list-group {
        margin-top: 1rem
    }

    .dx-menu .list-group-item:first-child {
        border-top-right-radius: 0;
        border-top-left-radius: 0
    }

    .dx-menu .list-group-item:last-child {
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0
    }

    .dx-menu .list-group-item {
        border: 1px solid #e2e2e2;
        border-left: 0;
        border-right: 0;
        color: #333
    }

    .dx-menu .list-group-item.active {
        border: 1px solid #666;
        background-color: #666;
        color: #fff
    }

    .navbar {
        padding: 0;
        background-color: #333
    }

    .navbar .dx-container-column {
        padding: .5rem 1rem
    }

    @media(min-width:992px) {
        .navbar .dx-container-column {
            padding: .5rem 0
        }
    }

    .navbar .nav-link {
        color: #fff !important
    }

    .dx-navbar-brand-frame {
        position: absolute;
        left: 30%;
        width: 40%;
        text-align: center
    }

    @media(min-width:796px) {
        .dx-navbar-brand-frame {
            position: static;
            left: auto;
            width: auto;
            text-align: left
        }
    }

    .navbar-brand {
        margin-right: 0;
        padding-top: 0;
        padding-bottom: 0;
        font-size: 1.7rem;
        font-weight: bold;
        color: #fff !important
    }

    @media(min-width:796px) {
        .dx-search-toggler {
            display: none
        }
    }

    .dx-search {
        width: 100%
    }

    @media(min-width:796px) {
        .dx-search {
            display: block;
            width: auto
        }
    }

    .dx-search .form-inline {
        padding-top: .5rem;
        padding-bottom: .5rem
    }

    @media(min-width:796px) {
        .dx-search .form-inline {
            padding-top: 0;
            padding-bottom: 0
        }
    }

    @media(min-width:576px) {
        .dx-search .form-inline .input-group {
            width: 100%
        }
    }

    @media(min-width:796px) {
        .dx-search .form-inline .input-group {
            width: 500px
        }
    }

    @media(min-width:992px) {
        .dx-search .form-inline .input-group {
            width: 600px
        }
    }

    .dx-search-input {
        border: 0;
        padding-right: 0;
        line-height: 1.5
    }

    .dx-search .dx-clear-button {
        margin-right: 0 !important;
        border: 0
    }

    .dx-search-button {
        margin-left: 0 !important;
        border: 0
    }

    .dx-search-error {
        position: relative
    }

    .dx-search-error .dx-tooltip-pointer-top {
        position: absolute;
        top: -18px;
        left: 50%
    }

    .dx-footer {
        background-color: #666
    }

    .dx-footer .dx-container-column {
        padding: 1rem
    }

    @media(min-width:992px) {
        .dx-footer .dx-container-column {
            padding: 1rem 0
        }
    }

    .dx-footer a {
        color: #fff
    }

    .dx-footer-menu-primary {
        text-align: center
    }

    @media(min-width:576px) {
        .dx-footer-menu-primary {
            float: left
        }
    }

    .dx-footer-menu-secondary {
        margin-top: 1rem;
        text-align: center
    }

    @media(min-width:576px) {
        .dx-footer-menu-secondary {
            margin-top: 0;
            float: right
        }
    }

    .dx-footer-menu-item+.dx-footer-menu-item {
        margin-left: 1.5rem
    }

    .dx-footer-copyright {
        color: #fff
    }

    .dx-footer-rta {
        vertical-align: text-bottom
    }

    .dx-footer-rta-icon {
        height: 17px
    }
    form label:hover{
        background-color: #cccccc;
    }
    form label{
        cursor: pointer;
    }
</style>
<script src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/i18n/jquery.ui.datepicker-vi.js"></script>
<div class="row-fluid" style="margin-top: 20px;margin-bottom: 20px;">
    <?php     
    $buttons[]=array('onclick'=>'$("#excel").val("1");$("#form").submit();','label'=>'Xuất file excel');
    echo $this->toolbar($buttons);
    ?>
</div>
<form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->baseUrl('/thongke'); ?>" method="post">
<div class="row-fluid">
    <div class="col-lg-4 col-md-4">
        <strong>Từ ngày: </strong>
        <input type="text" id="tu_ngay_quyet_dinh" readonly="readonly" name="tu_ngay_quyet_dinh" value="<?php echo $this->tu_ngay_quyet_dinh;?>"/>
        
    </div>
    <div class="col-lg-4 col-md-4">
        <strong>Đến ngày: </strong>
        <input type="text" id="den_ngay_quyet_dinh" readonly="readonly" name="den_ngay_quyet_dinh" value="<?php echo $this->den_ngay_quyet_dinh;?>"/>
        
    </div>
</div>
    <input type="hidden" name="excel" id="excel" value="0"/>
</form>
<br><br><br>
<div class="row-fluid">
    <table class="table table-bordered" id="nanopool-table" style="display: none;">
            <thead>
                <th>Số quyết định</th>
                <th>Ngày tháng</th>
                <th>Nội dung dự toán</th>
                <th>Giá trị dự toán</th>
                <th>Người phụ trách</th>
            </thead>
            <tbody>
                <?php 
                    $sum=0;
                    foreach ($items as $item){
                        $sum+=$item['tong_tien'];
                        ?>
                    <tr>
                        <td style="width: 20%;text-align: center;">
                            <?php 
                            echo $item['so_quyet_dinh'];
                            ?>
                        </td>
                        <td>
                            <?php 
                            list($date,$time)= explode(" ", $item['ngay_quyet_dinh']);
                            list($y,$m,$d)= explode("-", $date);
                            echo "$d/$m/$y";
                            ?>
                        </td>
                        <td title="<?php echo $item['noi_dung_quyet_dinh'];?>">
                            <?php echo Core_Common_String::crop($item['noi_dung_quyet_dinh'], 20);?>
                        </td>
                        <td>
                            <?php echo number_format($item['tong_tien'],0,",",".");?>
                        </td>
                        <td>
                            <?php 
                            echo $item['danh_xung'].' '.$item['full_name'];
                            ?>
                        </td>
                        
                    </tr>
                    <?php 
                    }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">&nbsp;</td>
                    <td><?php echo number_format($sum,0,",",".");?></td>
                    <td>&nbsp;</td>
                </tr>
            </tfoot>
        </table>

</div>
<script type="text/javascript">
    $(window).load(function() {
          $('#nanopool-table').show();
          $('#nanopool-table').DataTable();
          $('#nanopool-table_filter').remove();//.find('input').eq(0).css('width','270px');
          
    });
    jQuery(function ($){
       $( "#tu_ngay_quyet_dinh,#den_ngay_quyet_dinh" ).datepicker({
           onClose:function (){
               $("#excel").val('0');
               $("#form").submit();
           },
          changeMonth: true,
          changeYear: true,
          dateFormat: "dd/mm/yy",
          showWeek: true,
            showOn: "button",
            buttonImage: "<?php echo $this->baseUrl('/images/calendar/calendar.gif');?>",
            buttonImageOnly: true,
            buttonText: 'Click để chọn ngày',
            option:$.datepicker.regional['vi']
        });
       
    });
</script>
