<?php 
$module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
?>
<nav class="navbar navbar-default" style="margin-bottom: 5px;">
    <div class="container-fluid">
        <ul class="nav navbar-nav" id="topnav">
            <?php 
            if($module=='default'){?>
            <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'index') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/">Trang chủ</a></li>
            <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'dtxd') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/dtxd">Mẫu dự toán xây dựng</a></li>                        
            <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'tb') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/tb">Mẫu thiết bị</a></li>                        
            <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'excel') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/excel">Nhập liệu thông số vào hệ thống</a></li>
            <?php
            }
            else { ?>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'user') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/user">User</a></li>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'homecontent') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/homecontent">Nội dung trang chủ</a></li>                                
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'image') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/image">Logo và hình nền</a></li>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'headerfooter') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/headerfooter">Phía trên và phía dưới</a></li>
            <?php 
            }
            ?>
        </ul>
    </div>
</nav>