<?php 
$items = $this->items;
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $identity = $auth->getIdentity();
}
else{
    $identity=NULL;
}

?>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <style>
        .dx-body {
            background-color: #f1f1f1
        }

        @media(min-width:992px) {
            .container {
                width: 960px
            }
        }

        .dx-content .dx-container-column {
            padding-top: .5rem;
            padding-bottom: .5rem;
            padding-left: 1rem;
            padding-right: 1rem
        }

        @media(min-width:400px) {
            .dx-content .dx-container-column {
                padding-top: .75rem;
                padding-bottom: .75rem;
                padding-left: 1.5rem;
                padding-right: 1.5rem
            }
        }

        @media(min-width:992px) {}

        .dx-container-row {
            padding-top: .5rem;
            padding-bottom: .5rem
        }

        @media(min-width:400px) {
            .dx-container-row {
                padding-top: .75rem;
                padding-bottom: .75rem
            }
        }

        .dx-container-padding {
            padding-top: .5rem
        }

        .dx-content .container {
            overflow: hidden;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
            background-color: #fff
        }

        @media(min-width:992px) {
            .dx-content .container {
                margin-top: 1rem;
                margin-bottom: 1rem
            }
        }

        .dx-vertical-item+.dx-vertical-item {
            margin-top: .75rem
        }

        .dx-separator {
            margin-left: -3rem;
            margin-right: -3rem;
            border-top: 1px solid #e2e2e2
        }

        @media(min-width:992px) {
            .dx-separator {
                margin-left: 0;
                margin-right: 0
            }
        }

        .dx-tooltip {
            border-radius: .25rem;
            padding: 1rem 1.25rem;
            background-color: #333;
            color: #fff
        }

        .dx-tooltip-pointer-top {
            border-top: 6px solid transparent;
            border-bottom: 12px solid #333;
            border-left: 6px solid transparent;
            border-right: 6px solid transparent
        }

        .dx-tooltip .close {
            color: #fff
        }

        .dx-tooltip .fa-li {
            line-height: 1.4
        }

        a.dx-tooltip-link {
            display: block;
            word-break: break-all
        }

        a.dx-tooltip-link {
            color: #7ac616
        }

        a.dx-tooltip-link:hover {
            color: #7ac616
        }

        a.dx-tooltip-link:active {
            color: #7ac616
        }

        .dx-menu {
            padding-top: 1rem;
            padding-bottom: 1rem
        }

        .dx-menu .list-group+.list-group {
            margin-top: 1rem
        }

        .dx-menu .list-group-item:first-child {
            border-top-right-radius: 0;
            border-top-left-radius: 0
        }

        .dx-menu .list-group-item:last-child {
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0
        }

        .dx-menu .list-group-item {
            border: 1px solid #e2e2e2;
            border-left: 0;
            border-right: 0;
            color: #333
        }

        .dx-menu .list-group-item.active {
            border: 1px solid #666;
            background-color: #666;
            color: #fff
        }

        .navbar {
            padding: 0;
            background-color: #333
        }

        .navbar .dx-container-column {
            padding: .5rem 1rem
        }

        @media(min-width:992px) {
            .navbar .dx-container-column {
                padding: .5rem 0
            }
        }

        .navbar .nav-link {
            color: #fff !important
        }

        .dx-navbar-brand-frame {
            position: absolute;
            left: 30%;
            width: 40%;
            text-align: center
        }

        @media(min-width:796px) {
            .dx-navbar-brand-frame {
                position: static;
                left: auto;
                width: auto;
                text-align: left
            }
        }

        .navbar-brand {
            margin-right: 0;
            padding-top: 0;
            padding-bottom: 0;
            font-size: 1.7rem;
            font-weight: bold;
            color: #fff !important
        }

        @media(min-width:796px) {
            .dx-search-toggler {
                display: none
            }
        }

        .dx-search {
            width: 100%
        }

        @media(min-width:796px) {
            .dx-search {
                display: block;
                width: auto
            }
        }

        .dx-search .form-inline {
            padding-top: .5rem;
            padding-bottom: .5rem
        }

        @media(min-width:796px) {
            .dx-search .form-inline {
                padding-top: 0;
                padding-bottom: 0
            }
        }

        @media(min-width:576px) {
            .dx-search .form-inline .input-group {
                width: 100%
            }
        }

        @media(min-width:796px) {
            .dx-search .form-inline .input-group {
                width: 500px
            }
        }

        @media(min-width:992px) {
            .dx-search .form-inline .input-group {
                width: 600px
            }
        }

        .dx-search-input {
            border: 0;
            padding-right: 0;
            line-height: 1.5
        }

        .dx-search .dx-clear-button {
            margin-right: 0 !important;
            border: 0
        }

        .dx-search-button {
            margin-left: 0 !important;
            border: 0
        }

        .dx-search-error {
            position: relative
        }

        .dx-search-error .dx-tooltip-pointer-top {
            position: absolute;
            top: -18px;
            left: 50%
        }

        .dx-footer {
            background-color: #666
        }

        .dx-footer .dx-container-column {
            padding: 1rem
        }

        @media(min-width:992px) {
            .dx-footer .dx-container-column {
                padding: 1rem 0
            }
        }

        .dx-footer a {
            color: #fff
        }

        .dx-footer-menu-primary {
            text-align: center
        }

        @media(min-width:576px) {
            .dx-footer-menu-primary {
                float: left
            }
        }

        .dx-footer-menu-secondary {
            margin-top: 1rem;
            text-align: center
        }

        @media(min-width:576px) {
            .dx-footer-menu-secondary {
                margin-top: 0;
                float: right
            }
        }

        .dx-footer-menu-item+.dx-footer-menu-item {
            margin-left: 1.5rem
        }

        .dx-footer-copyright {
            color: #fff
        }

        .dx-footer-rta {
            vertical-align: text-bottom
        }

        .dx-footer-rta-icon {
            height: 17px
        }
        
        form label:hover{
            background-color: #cccccc;
        }
        form label{
            cursor: pointer;
        }
    </style>
    <form method="POST" action="<?php echo $this->baseUrl();?>/tb">
        <?php if($this->keyword!=''){?>
        <div class="row" style="margin-bottom: 20px;">
            <div class="col-lg-12 col-md-12">
                <nav class="navbar navbar-default" style="margin-bottom: 5px;border: none;">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->baseUrl(); ?>/tb">Hiển thị tất cả thông tin như ban đầu</a></li>                        
                        </ul>
                </nav>
            </div>
        </div>
        <?php }?>
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="float-right collapse  dx-search">
                    <div class="input-group">
                        <input class="form-control dx-search-input" type="text" name="keyword" value="<?php echo $this->keyword;?>" maxlength="1024" placeholder="Nhập từ khóa vào đây để tìm kiếm" data-clear-input="true">
                        <div class="input-group-btn">
                            <button class="btn btn-secondary dx-clear-button" style="display: none;" type="button" data-clear-button="true">
                                <i class="fa fa-times-circle"></i>
                            </button>
                        </div>
                        <div class="input-group-btn"><button class="btn btn-secondary dx-search-button" type="submit"><i class="fa fa-search"></i></button></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12">
                <div class="col-lg-2 col-md-2">
                    <label>
                        <input type="radio" name="type" value="ten_vttb"<?php if($this->type=='ten_vttb') echo ' checked="checked"';?>/>
                        Tên VTTB
                    </label>
                </div>
                <div class="col-lg-3 col-md-3">
                    <label>
                        <input type="radio" name="type" value="dac_tinh_ky_thuat"<?php if($this->type=='dac_tinh_ky_thuat') echo ' checked="checked"';?>/>
                        Đặc tính kỹ thuật
                    </label>
                </div>
                <div class="col-lg-2 col-md-2">
                    <label>
                        <input type="radio" name="type" value="don_gia"<?php if($this->type=='don_gia') echo ' checked="checked"';?>/>
                        Đơn giá
                    </label>
                </div>
            </div>
        </div>
    </form>
<div class="row-fluid">
    <table class="table table-bordered" id="nanopool-table" style="display: none;">
            <thead>
                <th>Quyết định</th>
                <th>Tên VTTB</th>
                <th>Đặc tính kỹ thuật</th>
                <th>Đơn vị</th>
                <th>Đơn giá</th>
                <th>Số lượng</th>
                <th>Thành tiền</th>
                <?php 
                if(is_array($identity)&&$identity['is_download']=='1'){?>
                    <th>Download</th>
                <?php 
                }
                ?>
            </thead>
            <tbody>
                <?php 
                    foreach ($items as $item){?>
                    <tr id="thiet_bi_id_<?php echo $item['thiet_bi_id'];?>">
                        <td style="width: 20%;text-align: center;" title="<?php echo $item['noi_dung_quyet_dinh'];?>">
                            <?php 
                            echo $item['so_quyet_dinh'];
                            echo "<br>";
                            list($date,$time)= explode(" ", $item['ngay_quyet_dinh']);
                            list($y,$m,$d)= explode("-", $date);
                            echo "$d/$m/$y";
                            echo "<br>";
                            echo Core_Common_String::crop($item['noi_dung_quyet_dinh'], 20);
                            ?>
                        </td>
                        <td>
                            <?php echo $item['ten_vttb'];?>
                        </td>
                        <td>
                            <?php echo nl2br($item['dac_tinh_ky_thuat']);?>
                        </td>
                        <td>
                            <?php echo $item['don_vi'];?>
                        </td>
                        <td>
                            <?php 
                            if ($item['don_gia'] == 0) {
                                echo 0;
                            } else {
                                echo number_format(floatval($item['don_gia']), 0, ",", ".") ;
                            }
                            ?>
                        </td>
                        <td>
                            <?php 
                            if ($item['so_luong'] == 0) {
                                echo 0;
                            } else {
                                echo number_format(floatval($item['so_luong']), 0, ",", ".") ;
                            }
                            ?>
                        </td>
                        <td>
                            <?php 
                            if ($item['thanh_tien'] == 0) {
                                echo 0;
                            } else {
                                echo number_format(floatval($item['thanh_tien']), 0, ",", ".") ;
                            }
                            ?>
                        </td>
                        <?php 
                        if(is_array($identity)&&$identity['is_download']=='1'){?>
                            <td>
                                <div style="padding: 5px;margin-bottom: 10px;" title="Nhấn vào đây để download file excel">
                                    <button onclick="window.location='<?php echo $this->baseUrl();?>/tb/index/thiet_bi_id/<?php echo $item['thiet_bi_id'];?>/file_name/excel.xls';">Excel</button>
                                </div>
                                
                                <div style="padding: 5px;" title="Nhấn vào đây để download file pdf">
                                    <button onclick="window.location='<?php echo $this->baseUrl();?>/tb/index/thiet_bi_id/<?php echo $item['thiet_bi_id'];?>/file_name/pdf.pdf';">Pdf</button>
                                </div>
                                
                            </td>
                        <?php 
                        }
                        ?>
                    </tr>
                    <?php 
                    }
                ?>
            </tbody>
        </table>

</div>
<script>
    $(window).load(function() {
          $('#nanopool-table').show();
          $('#nanopool-table').DataTable();
          $('#nanopool-table_filter').find('input').eq(0).css('width','270px');
    });
    
    jQuery(function ($){
    });
</script>
