<?php 
$items = $this->items;
?>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">

    <script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <style>
        #nanopool-table tbody tr{
            cursor: pointer;
        }
        #nanopool-table tbody tr:hover{
            background-color: #cccccc;
        }
    </style>
<div class="row-fluid">
    <table class="table table-bordered" id="nanopool-table" style="display: none;">
            <thead>
            <th>Tên VTTB</th>
            <th>Đặc tính kỹ thuật</th>
            <th>Đơn vị</th>
            <th>Đơn giá</th>
            <th>Số lượng</th>
            <th>Thành tiền</th>
            </thead>
            <tbody>
                <?php 
                    foreach ($items as $item){?>
                    <tr title="Nhấn vào đây để download file excel" id="thiet_bi_id_<?php echo $item['thiet_bi_id'];?>">
                        <td>
                            <?php echo $item['ten_vttb'];?>
                        </td>
                        <td>
                            <?php echo nl2br($item['dac_tinh_ky_thuat']);?>
                        </td>
                        <td>
                            <?php echo $item['don_vi'];?>
                        </td>
                        <td>
                            <?php echo $item['don_gia'];?>
                        </td>
                        <td>
                            <?php echo $item['so_luong'];?>
                        </td>
                        <td>
                            <?php echo $item['thanh_tien'];?>
                        </td>
                    </tr>
                    <?php 
                    }
                ?>
            </tbody>
        </table>

</div>
    <form method="POST" id="download">
        <input type="hidden" name="thiet_bi_id" id="thiet_bi_id"/>
    </form>
<script>
    $(window).load(function() {
          $('#nanopool-table').show();
          $('#nanopool-table').DataTable();
          $('#nanopool-table_filter').find('input').eq(0).css('width','270px');
    });
    
    jQuery(function ($){
       $("#nanopool-table tbody tr").click(function (){
           id=$(this).attr('id');
           temp=id.split('_id_');//id sẽ là thiet_bi_id_xxx
           id=temp[1];
           $("#thiet_bi_id").val(id);
           $("form#download").submit();
       });
    });
</script>
