<?php 
$items = $this->items;
?>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">

    <script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <style>
        #nanopool-table tbody tr{
            cursor: pointer;
        }
        #nanopool-table tbody tr:hover{
            background-color: #cccccc;
        }
    </style>
<div class="row-fluid">
    <table class="table table-bordered" id="nanopool-table" style="display: none;">
            <thead>
            <th>Ký hiệu</th>
            <th>Đối tượng</th>
            <th>Đơn vị</th>
            <th>Đơn giá</th>
            <th>Khối lượng</th>
            <th>Thành tiền</th>
            </thead>
            <tbody>
                <?php 
                    foreach ($items as $item){?>
                    <tr title="Nhấn vào đây để download file excel" id="du_toan_id_<?php echo $item['du_toan_id'];?>">
                        <td>
                            <?php echo $item['ky_hieu'];?>
                        </td>
                        <td>
                            <?php echo $item['doi_tuong'];?>
                        </td>
                        <td>
                            <?php echo $item['don_vi'];?>
                        </td>
                        <td>
                            <?php echo $item['don_gia'];?>
                        </td>
                        <td>
                            <?php echo $item['khoi_luong'];?>
                        </td>
                        <td>
                            <?php echo $item['thanh_tien'];?>
                        </td>
                    </tr>
                    <?php 
                    }
                ?>
            </tbody>
        </table>

</div>
    <form method="POST" id="download">
        <input type="hidden" name="du_toan_id" id="du_toan_id"/>
    </form>
<script>
    $(window).load(function() {
          $('#nanopool-table').show();
          $('#nanopool-table').DataTable();
          $('#nanopool-table_filter').find('input').eq(0).css('width','270px');
    });
    
    jQuery(function ($){
       $("#nanopool-table tbody tr").click(function (){
           id=$(this).attr('id');
           temp=id.split('_id_');//id sẽ là du_toan_id_xxx
           id=temp[1];
           $("#du_toan_id").val(id);
           $("form#download").submit();
       });
    });
</script>
