<?php 
$items = $this->items;
?>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <style>
        #nanopool-table tbody tr{
            cursor: pointer;
        }
        #nanopool-table tbody tr:hover{
            background-color: #cccccc;
        }
        .dx-body {
            background-color: #f1f1f1
        }

        @media(min-width:992px) {
            .container {
                width: 960px
            }
        }

        .dx-content .dx-container-column {
            padding-top: .5rem;
            padding-bottom: .5rem;
            padding-left: 1rem;
            padding-right: 1rem
        }

        @media(min-width:400px) {
            .dx-content .dx-container-column {
                padding-top: .75rem;
                padding-bottom: .75rem;
                padding-left: 1.5rem;
                padding-right: 1.5rem
            }
        }

        @media(min-width:992px) {}

        .dx-container-row {
            padding-top: .5rem;
            padding-bottom: .5rem
        }

        @media(min-width:400px) {
            .dx-container-row {
                padding-top: .75rem;
                padding-bottom: .75rem
            }
        }

        .dx-container-padding {
            padding-top: .5rem
        }

        .dx-content .container {
            overflow: hidden;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
            background-color: #fff
        }

        @media(min-width:992px) {
            .dx-content .container {
                margin-top: 1rem;
                margin-bottom: 1rem
            }
        }

        .dx-vertical-item+.dx-vertical-item {
            margin-top: .75rem
        }

        .dx-separator {
            margin-left: -3rem;
            margin-right: -3rem;
            border-top: 1px solid #e2e2e2
        }

        @media(min-width:992px) {
            .dx-separator {
                margin-left: 0;
                margin-right: 0
            }
        }

        .dx-tooltip {
            border-radius: .25rem;
            padding: 1rem 1.25rem;
            background-color: #333;
            color: #fff
        }

        .dx-tooltip-pointer-top {
            border-top: 6px solid transparent;
            border-bottom: 12px solid #333;
            border-left: 6px solid transparent;
            border-right: 6px solid transparent
        }

        .dx-tooltip .close {
            color: #fff
        }

        .dx-tooltip .fa-li {
            line-height: 1.4
        }

        a.dx-tooltip-link {
            display: block;
            word-break: break-all
        }

        a.dx-tooltip-link {
            color: #7ac616
        }

        a.dx-tooltip-link:hover {
            color: #7ac616
        }

        a.dx-tooltip-link:active {
            color: #7ac616
        }

        .dx-menu {
            padding-top: 1rem;
            padding-bottom: 1rem
        }

        .dx-menu .list-group+.list-group {
            margin-top: 1rem
        }

        .dx-menu .list-group-item:first-child {
            border-top-right-radius: 0;
            border-top-left-radius: 0
        }

        .dx-menu .list-group-item:last-child {
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0
        }

        .dx-menu .list-group-item {
            border: 1px solid #e2e2e2;
            border-left: 0;
            border-right: 0;
            color: #333
        }

        .dx-menu .list-group-item.active {
            border: 1px solid #666;
            background-color: #666;
            color: #fff
        }

        .navbar {
            padding: 0;
            background-color: #333
        }

        .navbar .dx-container-column {
            padding: .5rem 1rem
        }

        @media(min-width:992px) {
            .navbar .dx-container-column {
                padding: .5rem 0
            }
        }

        .navbar .nav-link {
            color: #fff !important
        }

        .dx-navbar-brand-frame {
            position: absolute;
            left: 30%;
            width: 40%;
            text-align: center
        }

        @media(min-width:796px) {
            .dx-navbar-brand-frame {
                position: static;
                left: auto;
                width: auto;
                text-align: left
            }
        }

        .navbar-brand {
            margin-right: 0;
            padding-top: 0;
            padding-bottom: 0;
            font-size: 1.7rem;
            font-weight: bold;
            color: #fff !important
        }

        @media(min-width:796px) {
            .dx-search-toggler {
                display: none
            }
        }

        .dx-search {
            width: 100%
        }

        @media(min-width:796px) {
            .dx-search {
                display: block;
                width: auto
            }
        }

        .dx-search .form-inline {
            padding-top: .5rem;
            padding-bottom: .5rem
        }

        @media(min-width:796px) {
            .dx-search .form-inline {
                padding-top: 0;
                padding-bottom: 0
            }
        }

        @media(min-width:576px) {
            .dx-search .form-inline .input-group {
                width: 100%
            }
        }

        @media(min-width:796px) {
            .dx-search .form-inline .input-group {
                width: 500px
            }
        }

        @media(min-width:992px) {
            .dx-search .form-inline .input-group {
                width: 600px
            }
        }

        .dx-search-input {
            border: 0;
            padding-right: 0;
            line-height: 1.5
        }

        .dx-search .dx-clear-button {
            margin-right: 0 !important;
            border: 0
        }

        .dx-search-button {
            margin-left: 0 !important;
            border: 0
        }

        .dx-search-error {
            position: relative
        }

        .dx-search-error .dx-tooltip-pointer-top {
            position: absolute;
            top: -18px;
            left: 50%
        }

        .dx-footer {
            background-color: #666
        }

        .dx-footer .dx-container-column {
            padding: 1rem
        }

        @media(min-width:992px) {
            .dx-footer .dx-container-column {
                padding: 1rem 0
            }
        }

        .dx-footer a {
            color: #fff
        }

        .dx-footer-menu-primary {
            text-align: center
        }

        @media(min-width:576px) {
            .dx-footer-menu-primary {
                float: left
            }
        }

        .dx-footer-menu-secondary {
            margin-top: 1rem;
            text-align: center
        }

        @media(min-width:576px) {
            .dx-footer-menu-secondary {
                margin-top: 0;
                float: right
            }
        }

        .dx-footer-menu-item+.dx-footer-menu-item {
            margin-left: 1.5rem
        }

        .dx-footer-copyright {
            color: #fff
        }

        .dx-footer-rta {
            vertical-align: text-bottom
        }

        .dx-footer-rta-icon {
            height: 17px
        }
        
        form label:hover{
            background-color: #cccccc;
        }
        form label{
            cursor: pointer;
        }
        
       
    </style>
    <form method="POST" action="<?php echo $this->baseUrl();?>/dtxd">
        <?php if($this->keyword!=''){?>
        <div class="row" style="margin-bottom: 20px;">
            <div class="col-lg-12 col-md-12">
                <nav class="navbar navbar-default" style="margin-bottom: 5px;border: none;">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->baseUrl(); ?>/dtxd">Hiển thị tất cả thông tin như ban đầu</a></li>                        
                        </ul>
                </nav>
            </div>
        </div>
        <?php }?>
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="float-right collapse  dx-search">
                    <div class="input-group">
                        <input class="form-control dx-search-input" type="text" name="keyword" value="<?php echo $this->keyword;?>" maxlength="1024" placeholder="Nhập từ khóa vào đây để tìm kiếm" data-clear-input="true">
                        <div class="input-group-btn">
                            <button class="btn btn-secondary dx-clear-button" style="display: none;" type="button" data-clear-button="true">
                                <i class="fa fa-times-circle"></i>
                            </button>
                        </div>
                        <div class="input-group-btn"><button class="btn btn-secondary dx-search-button" type="submit"><i class="fa fa-search"></i></button></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12">
                <div class="col-lg-2 col-md-2">
                    <label>
                        <input type="radio" name="type" value="ky_hieu"<?php if($this->type=='ky_hieu') echo ' checked="checked"';?>/>
                        Ký hiệu
                    </label>
                </div>
                <div class="col-lg-2 col-md-2">
                    <label>
                        <input type="radio" name="type" value="doi_tuong"<?php if($this->type=='doi_tuong') echo ' checked="checked"';?>/>
                        Đối tượng
                    </label>
                </div>
                <div class="col-lg-2 col-md-2">
                    <label>
                        <input type="radio" name="type" value="don_vi"<?php if($this->type=='don_vi') echo ' checked="checked"';?>/>
                        Đơn vị
                    </label>
                </div>
                <div class="col-lg-2 col-md-2">
                    <label>
                        <input type="radio" name="type" value="don_gia"<?php if($this->type=='don_gia') echo ' checked="checked"';?>/>
                        Đơn giá
                    </label>
                </div>
                <div class="col-lg-2 col-md-2">
                    <label>
                        <input type="radio" name="type" value="khoi_luong"<?php if($this->type=='khoi_luong') echo ' checked="checked"';?>/>
                        Khối lượng
                    </label>
                </div>
            </div>
        </div>
    </form>
<div class="row-fluid">
    <table class="table table-bordered" id="nanopool-table" style="display: none;">
            <thead>
            <th>Ký hiệu</th>
            <th>Đối tượng</th>
            <th>Đơn vị</th>
            <th>Đơn giá</th>
            <th>Khối lượng</th>
            <th>Thành tiền</th>
            </thead>
            <tbody>
                <?php 
                    foreach ($items as $item){?>
                    <tr title="Nhấn vào đây để download file excel" id="du_toan_id_<?php echo $item['du_toan_id'];?>">
                        <td>
                            <?php echo $item['ky_hieu'];?>
                        </td>
                        <td>
                            <?php echo $item['doi_tuong'];?>
                        </td>
                        <td>
                            <?php echo $item['don_vi'];?>
                        </td>
                        <td>
                            <?php echo $item['don_gia'];?>
                        </td>
                        <td>
                            <?php echo $item['khoi_luong'];?>
                        </td>
                        <td>
                            <?php echo $item['thanh_tien'];?>
                        </td>
                    </tr>
                    <?php 
                    }
                ?>
            </tbody>
        </table>

</div>
    <form method="POST" id="download">
        <input type="hidden" name="du_toan_id" id="du_toan_id"/>
    </form>
<script>
    $(window).load(function() {
          $('#nanopool-table').show();
          $('#nanopool-table').DataTable();
          $('#nanopool-table_filter').find('input').eq(0).css('width','270px');
    });
    
    jQuery(function ($){
       $("#nanopool-table tbody tr").click(function (){
           id=$(this).attr('id');
           temp=id.split('_id_');//id sẽ là du_toan_id_xxx
           id=temp[1];
           $("#du_toan_id").val(id);
           $("form#download").submit();
       });
    });
</script>
